# -*- coding: utf-8 -*-
"""EvoTranscrição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVph_qO3TI1mUbDFgqgnUBIUNq6YGEd-
"""

pip install openai-whisper yt-dlp

!apt update
!apt install ffmpeg -y

import whisper
import yt_dlp
import os

def baixar_audio(url):
    print("🎬 Baixando áudio do YouTube...")

    yt_dlp_opts = {
        'format': 'bestaudio/best',
        'outtmpl': 'audio.%(ext)s',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
    }
    with yt_dlp.YoutubeDL(yt_dlp_opts) as ydl:
        ydl.download([url])

    return "audio.mp3"

#vamos transcrever o audio usando o modelo whisper

def transcrever(audio):
    print("Carregando modelo Whisper...")
    model = whisper.load_model("tiny")
    print("Transcrevendo áudio...")
    resultado = model.transcribe(audio, language="pt")
    texto = resultado["text"]
    #salvar txt
    with open("transcricao.txt", "w", encoding="utf-8") as f:
        f.write(texto)
    print("✅ Transcrição finalizada com sucesso! Veja o arquivo transcricao.txt")

url = input("Cole o link do vídeo do YouTube: ")
audio = baixar_audio(url)
transcrever(audio)

#remover arquivo de audio temporario
os.remove(audio)
print("🧹 Arquivo de áudio temporário removido.")